### ISSUE TITLE
[NEW-INITIATIVE]: מילות הברזל עדכון

### ISSUE THREAD

**Issue by reututy** [4tals/LinksForIsrael#353]
### Initiative Name

Words of Iron

### Initiative Description

Boost Israel's Voice on Social Media with a Single Click!

### Initiative Details

Boost Israel's Voice on Social Media with a Single Click!

### Initiative Validation Details

https://www.calcalistech.com/ctechnews/article/bj9qt8hzt

### Initiative Category

StrategicCommunication/Tools

### Initiative main URL

https://www.wordsofiron.com/en

### Initiative Website

https://www.wordsofiron.com/en

**Comment by ohadschn** [comment]
@reututy 
We already had a ticket for this: https://github.com/4tals/LinksForIsrael/issues/105 however, since it was in the old format, I've closed the other one and left this one - keep in mind though that it's best to use GitHub search to make sure we don't have duplicates (for next time)

In addition, note that I've edited your post to provide a reputable source for validation (calcalist)
